### ISSUE TITLE
For a custom monocular video, is there any recommended model for generating mask with good effect?

### ISSUE THREAD

**Issue by sycamore27** [chungyiweng/humannerf#10]

**Comment by chungyiweng** [comment]
I manually revised the human segmentations for YouTube videos.

If looking for a fully automatic human segmentation method, I recommend [background matting](https://github.com/PeterL1n/BackgroundMattingV2) if a background image is available; otherwise, you might want to try [robust video matting](https://github.com/PeterL1n/RobustVideoMatting).
