### ISSUE TITLE
question about Rh and TH

### ISSUE THREAD

**Issue by ssy-sheshe** [chungyiweng/humannerf#5]
(1) Not sure what coordinate system Rh and Th are represented in. Can you please elaborate it for me?
(2) [def apply_global_tfm_to_camera(E, Rh, Th):](https://github.com/chungyiweng/humannerf/blob/7389c4049c0d5b14afdbac41a605ddad9d51dd4a/core/utils/camera_util.py#L112) how does this function get to calculate the matrix of the world2camera coordinate system?
Thanks!

**Comment by chungyiweng** [comment]
Thanks, @YxZhxn, for your response.

Yes, it is correct. Rh and Th are the global rotation and translation of the SMPL model. As mentioned in the paper, instead of rotating the subject, we choose to rotate the camera. The function `apply_global_tfm_to_camera(E, Rh, Th)` is for this and outputs the camera extrinsic matrix after the transformation.
